# configuration for "master" branch 
-
  branches:
      only:
        - master
  version: 1.0.{build}
  image: Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: Kse62H9lWHIwjsqpi2ih1efUnHc5R6VfIzu1Nfr/CXcJSKPkH8EGElCIxvP43/Oh
  
  install:
  - ps: nuget sources add -Name XamarinSyncfusion -Source http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin

  
  build_script:
  - ps: .\build.ps1 -verbosity Diagnostic
  test: off
-
  branches:
      only:
        - develop
  version: 1.0.{build}
  image: Visual Studio 2017
  environment:
    NUGET_SOURCE: https://www.myget.org/F/martijn00/api/v2/package
    NUGET_APIKEY:
      secure: 0PNC9eZWAinI1KkE9usbhPAwF1wudL5GJi6lJn9Ylb67M7SE17LIXBoMHuRKJaLE
  build_script:
  - ps: .\build.ps1 -verbosity Diagnostic
  test: off
